language: cpp

compiler:
        - gcc

before_install:
        - sudo add-apt-repository -y ppa:andykimpe/cmake
        - sudo add-apt-repository -y ppa:boost-latest/ppa
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -qq update

install:
        - sudo apt-get install cmake 
        - sudo apt-get install -qq boost1.56
        - wget ftp://gsapubftp-anonymous@ftp.broadinstitute.org/travis/gcc_4.9.1-1_amd64.deb
        - sudo apt-get remove cpp libffi-dev
        - sudo dpkg --install gcc_4.9.1-1_amd64.deb
        - sudo rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        - export LD_LIBRARY_PATH=/usr/lib64
        - sudo ln -s /usr/lib64/libstd* /usr/lib/x86_64-linux-gnu/

script: 
        - cmake .
        - make

after_success:
        - sudo pip install cpp-coveralls
        - coveralls -r . -e CMakeFiles --gcov-options '\-lp'
